spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=stay_fit
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        type: trace
        default_schema: stay_fit

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG